### ISSUE TITLE
Account snapshot fails on malfored Matrix ID

### ISSUE THREAD

**Issue by gsouquet** [matrix-org/complement#139]
**Describe the bug**

Account snapshot fails when it encounters an invalid Matrix ID `@signalbot` in this case where the suffix `:homeserver.tld` is somehow missing

**To Reproduce**
1. Remove the `:homeserver.tld` bit in a read receipt event in `sync_snapshot.json`
2. Run the `account-snapshot` script again

**Expected behavior**
The event should probably be dropped

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Version: latest

**Additional context**

```
2021/06/28 14:02:03 Invalid matrix identifier: @signalbot
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1291501]

goroutine 1 [running]:
github.com/matrix-org/complement/cmd/account-snapshot/internal.ConvertToBlueprint(0x0, 0x13213ad, 0x3, 0xc000c9c0c0, 0xc, 0xc000711770)
        /path/to/complement/cmd/account-snapshot/internal/blueprint.go:24 +0x41
main.main()
        /path/to/complement/cmd/account-snapshot/main.go:80 +0x4cf
```

**Comment by gsouquet** [comment]
The issue was unrelated to what was described above and was fixed as part of 5b9f5dd98b9e12b2e026b26bce2a0b1a32e4fdd4
