### ISSUE TITLE
We don't seem to get logs if the tests time out

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/complement#394]
Instead we just get a panic and the stack traces for *all* goroutines.

e.g. https://github.com/matrix-org/synapse/runs/6877956238?check_suite_focus=true

**Comment by DMRobertson** [comment]
Additionally, the test is reported as taking 0 seconds rather then 10 minutes. Not sure if this is within our control though.

```
❌ TestRestrictedRoomsRemoteJoinFailOverInMSC3787Room (0s)
  2022/06/13 13:27:18 Sharing [SERVER_NAME=hs1 SYNAPSE_COMPLEMENT_USE_WORKERS= SYNAPSE_COMPLEMENT_DATABASE=postgres] host environment variables with container
  2022/06/13 13:27:27 Sharing [SERVER_NAME=hs2 SYNAPSE_COMPLEMENT_USE_WORKERS= SYNAPSE_COMPLEMENT_DATABASE=postgres] host environment variables with container
  panic: test timed out after 10m0s
```

**Comment by kegsay** [comment]
This probably isn't a bug. If a test times out out via the go-level timeout (set via `go test -timeout`, which defaults to 10 minutes) then this likely indicates a programming error rather than a faulty HS implementation. Therefore, printing goroutine stacks is actually useful at that point to debug why things ground to a halt. In this particular case, the relevant goroutines are:
```
  goroutine 6804 [semacquire]:
  sync.runtime_Semacquire(0x0)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/sema.go:56 +0x25
  sync.(*WaitGroup).Wait(0xc000d97080)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/sync/waitgroup.go:130 +0x71
  github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy(0xc000fd1140, {0xa72da8, 0xc0000ae000}, {0x9c2c29, 0x1})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:146 +0x62b
  github.com/matrix-org/complement/tests.Deploy(0xc001182d00, {{0x9c2c29, 0x1f}, {0xc0000b62c0, 0x2, 0x2}, {0x0, 0x0, 0x0}})
  	/home/runner/work/synapse/synapse/complement/tests/main_test.go:68 +0x256
  github.com/matrix-org/complement/tests.TestRestrictedRoomsSpacesSummaryFederation(0xc001182d00)
  	/home/runner/work/synapse/synapse/complement/tests/restricted_room_hierarchy_test.go:119 +0x85
  testing.tRunner(0xc001182d00, 0x9e0930)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/testing/testing.go:1259 +0x102
  created by testing.(*T).Run
  	/opt/hostedtoolcache/go/1.17.11/x64/src/testing/testing.go:1306 +0x35a
```
Blocked on calling `Deploy` - https://github.com/matrix-org/complement/blob/main/tests/restricted_room_hierarchy_test.go#L119

```
  goroutine 6807 [select]:
  net/http.(*persistConn).roundTrip(0xc0013f8fc0, 0xc000cbb300)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/transport.go:2614 +0x97d
  net/http.(*Transport).roundTrip(0xc001165a40, 0xc00107ad00)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/transport.go:594 +0x7d1
  net/http.(*Transport).RoundTrip(0x30, 0xa656a0)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/roundtrip.go:18 +0x19
  net/http.send(0xc00107ad00, {0xa656a0, 0xc001165a40}, {0x9a2aa0, 0x1, 0x0})
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:252 +0x5d8
  net/http.(*Client).send(0xc0010a8a80, 0xc00107ad00, {0x59, 0x14, 0x0})
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:176 +0x9b
  net/http.(*Client).do(0xc0010a8a80, 0xc00107ad00)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:725 +0x908
  net/http.(*Client).Do(...)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:593
  github.com/docker/docker/client.(*Client).doRequest(0xc000d97080, {0xa72da8, 0xc0000ae000}, 0xc00107ac00)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:125 +0x2a8
  github.com/docker/docker/client.(*Client).sendRequest(0x9bb9c4, {0xa72da8, 0xc0000ae000}, {0x9b3a33, 0x3}, {0xc001aae720, 0x7f1dcb826400}, 0x0, {0xa64e60, 0xc000f5cd20}, ...)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:113 +0xe6
  github.com/docker/docker/client.(*Client).putRaw(...)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:55
  github.com/docker/docker/client.(*Client).CopyToContainer(0xc000dae000, {0xa72da8, 0xc0000ae000}, {0xc000d2a7c0, 0x40}, {0xa5de20, 0x1}, {0xa64e60, 0xc000f5cd20}, {0x0, ...})
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/container_copy.go:47 +0x35c
  github.com/matrix-org/complement/internal/docker.copyToContainer(0xc000b5ebe0, {0xc000d2a7c0, 0x40}, {0x9bbda1, 0x15}, {0xc000dae000, 0x0, 0xfc0})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:421 +0x2e8
  github.com/matrix-org/complement/internal/docker.deployImage(0x20, {0xc00191f8b0, 0xc000d48a90}, {0xc000d2a6c0, 0x3b}, {0x9b3a9f, 0x3}, {0x9c2c29, 0x1f}, {0xc001162cda, ...}, ...)
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:282 +0xbf5
  github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy.func1({0xffffffffffffffff, 0x62a85c35, {0xc00191f8b0, 0x47}, 0xc0010a8fc0, {0xc00191f950, 0x47}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:117 +0x3a5
  github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy.func2({0xffffffffffffffff, 0x62a85c35, {0xc00191f8b0, 0x47}, 0xc0010a8fc0, {0xc00191f950, 0x47}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:138 +0x75
  created by github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:137 +0x608
```
Blocking whilst copying CA cert files - https://github.com/matrix-org/complement/blob/main/internal/docker/deployer.go#L283

Likewise another goroutine is doing the same thing:
```
  goroutine 6806 [select]:
  net/http.(*persistConn).roundTrip(0xc0013f9440, 0xc000fd1800)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/transport.go:2614 +0x97d
  net/http.(*Transport).roundTrip(0xc001165a40, 0xc000f8f600)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/transport.go:594 +0x7d1
  net/http.(*Transport).RoundTrip(0x30, 0xa656a0)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/roundtrip.go:18 +0x19
  net/http.send(0xc000f8f600, {0xa656a0, 0xc001165a40}, {0x9a2aa0, 0x1, 0x0})
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:252 +0x5d8
  net/http.(*Client).send(0xc0010a8a80, 0xc000f8f600, {0x59, 0x14, 0x0})
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:176 +0x9b
  net/http.(*Client).do(0xc0010a8a80, 0xc000f8f600)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:725 +0x908
  net/http.(*Client).Do(...)
  	/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/client.go:593
  github.com/docker/docker/client.(*Client).doRequest(0xc000d97080, {0xa72da8, 0xc0000ae000}, 0xc000f8f500)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:125 +0x2a8
  github.com/docker/docker/client.(*Client).sendRequest(0x9bb9c4, {0xa72da8, 0xc0000ae000}, {0x9b3a33, 0x3}, {0xc000db6120, 0x7f1dcb827500}, 0x0, {0xa64e60, 0xc0010a95c0}, ...)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:113 +0xe6
  github.com/docker/docker/client.(*Client).putRaw(...)
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/request.go:55
  github.com/docker/docker/client.(*Client).CopyToContainer(0xc000e65000, {0xa72da8, 0xc0000ae000}, {0xc000e02e00, 0x40}, {0xa5de20, 0x1}, {0xa64e60, 0xc0010a95c0}, {0x0, ...})
  	/home/runner/go/pkg/mod/github.com/docker/docker@v20.10.16+incompatible/client/container_copy.go:47 +0x35c
  github.com/matrix-org/complement/internal/docker.copyToContainer(0xc000b5ebe0, {0xc000e02e00, 0x40}, {0x9bbda1, 0x15}, {0xc000e65000, 0x0, 0xfc0})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:421 +0x2e8
  github.com/matrix-org/complement/internal/docker.deployImage(0x3a, {0xc00191f7c0, 0x7f1df22d35b8}, {0xc000e02d80, 0x3b}, {0x9b3a9f, 0x3}, {0x9c2c29, 0x1f}, {0xc001162c7c, ...}, ...)
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:282 +0xbf5
  github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy.func1({0xffffffffffffffff, 0x62a85c3a, {0xc00191f7c0, 0x47}, 0xc0010a8f90, {0xc00191f860, 0x47}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:117 +0x3a5
  github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy.func2({0xffffffffffffffff, 0x62a85c3a, {0xc00191f7c0, 0x47}, 0xc0010a8f90, {0xc00191f860, 0x47}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:138 +0x75
  created by github.com/matrix-org/complement/internal/docker.(*Deployer).Deploy
  	/home/runner/work/synapse/synapse/complement/internal/docker/deployer.go:137 +0x608
```

(you can generally quickly identify relevant goroutines by grepping for 'complement')

This may point to a problem with the Docker client / server when trying to copy the exact same bytes to different containers.

**Comment by erikjohnston** [comment]
So are you saying that it *is* actually printing out all of the logs for the test run?

**Comment by erikjohnston** [comment]
Well, perhaps, but can't we have both? Certainly when we had time outs in SyTest the logs were helpful :shrug:

**Comment by kegsay** [comment]
Not easily unfortunately. The goroutine which panics is in the guts of the core Go test library, so you cannot `defer recover` it. The hacky way to do this would be to set a timeout manually slightly lower than `-timeout` and fail before the Go test library fails us.

**Comment by richvdh** [comment]
if this is unactionable, let's close it?
